Repository ctreminiom/go-atlassian, pull requests merged in 2023-09, with the labels that each got.

#244 :sparkles: Added the Bitbucket Workspace implementation.
  bitbucket/api_client_impl.go
  bitbucket/api_client_impl_test.go
  bitbucket/internal/authentication_impl.go
  bitbucket/internal/authentication_impl_test.go
  bitbucket/internal/workspace_impl.go
  bitbucket/internal/workspace_impl_test.go
  bitbucket/internal/workspace_permissions_impl.go
  bitbucket/internal/workspace_permissions_impl_test.go
  bitbucket/internal/workspace_webhooks_impl.go
  bitbucket/internal/workspace_webhooks_impl_test.go
  pkg/infra/models/bitbucket_branch.go
  pkg/infra/models/bitbucket_projects.go
  pkg/infra/models/bitbucket_repository.go
  pkg/infra/models/bitbucket_webhooks.go
  pkg/infra/models/bitbucket_workspace.go
  pkg/infra/models/bitbucket_workspace_membership.go
  pkg/infra/models/errors.go
  service/bitbucket/workspace.go
Labels: enhancement, bitbucket

#243 :boom: Improved the SM.Request.Create() method.
  jira/sm/internal/request_impl.go
  jira/sm/internal/request_impl_test.go
  pkg/infra/models/errors.go
  pkg/infra/models/sm_request_field.go
  pkg/infra/models/sm_request_field_test.go
  service/sm/request.go
Labels: enhancement, Confluence, breaking-change

#241 Fix Issue #240: Adjust SpaceSchemeV2 `id` & `homepageID` Types
  confluence/internal/space_v2_impl_test.go
  pkg/infra/models/confluence_space_v2.go
Labels: Confluence, breaking-change

#245 :memo: Added the Bitbucket row on the README.md
  README.md
Labels: documentation, bitbucket

#230 :sparkles: Extract customfields from buffer support
  pkg/infra/models/agile_sprint.go
  pkg/infra/models/errors.go
  pkg/infra/models/jira_customFields.go
  pkg/infra/models/jira_customFields_test.go
  pkg/infra/models/jira_issue_custom_fields.go
  pkg/infra/models/jira_issue_custom_fields_test.go
  pkg/infra/models/sm_request_field.go
  pkg/infra/models/sm_request_field_test.go
Labels: feature
