Repository ctreminiom/go-atlassian, pull requests merged in 2024-07, with the labels that each got.

#289 Added parse function for tempo account
  pkg/infra/models/errors.go
  pkg/infra/models/jira_field.go
  pkg/infra/models/jira_issue_custom_fields_tempo.go
  pkg/infra/models/jira_issue_custom_fields_tempo_test.go
  pkg/infra/models/jira_issue_custom_fields_test.go
Labels: enhancement, Jira Software Cloud

#288 Added GroupUserPicker service & Find funtion
  go.mod
  go.sum
  jira/internal/group_user_picker_impl.go
  jira/internal/group_user_picker_impl_test.go
  jira/v2/api_client_impl.go
  jira/v3/api_client_impl.go
  pkg/infra/models/errors.go
  pkg/infra/models/jira_group_user_picker.go
  service/jira/group_user_picker.go
Labels: enhancement, V2, V3

#285 Added tests for parse request type & fixed test naming
  pkg/infra/models/errors.go
  pkg/infra/models/jira_issue_custom_fields.go
  pkg/infra/models/jira_issue_custom_fields_test.go
Labels: enhancement

#269 Fixed initialism in models
  assets/internal/object_impl_test.go
  assets/internal/object_type_attribute_impl_test.go
  assets/internal/object_type_impl_test.go
  jira/internal/field_context_option_impl_test.go
  jira/internal/team_impl_test.go
  pkg/infra/models/assets_object.go
  pkg/infra/models/assets_object_schema.go
  pkg/infra/models/assets_object_type.go
  pkg/infra/models/assets_ticket.go
  pkg/infra/models/jira_field.go
  pkg/infra/models/jira_field_context.go
  pkg/infra/models/jira_field_context_option.go
  pkg/infra/models/jira_filter.go
  pkg/infra/models/jira_issue_custom_fields_test.go
  pkg/infra/models/jira_issue_type_scheme.go
  pkg/infra/models/jira_issue_type_screen_scheme.go
  pkg/infra/models/jira_issue_v2.go
  pkg/infra/models/jira_issue_v3.go
  pkg/infra/models/jira_links.go
  pkg/infra/models/jira_notification_scheme.go
  pkg/infra/models/jira_project.go
  pkg/infra/models/jira_teams.go
  pkg/infra/models/jira_user.go
  pkg/infra/models/jira_workflow_scheme.go
  pkg/infra/models/sm_customer.go
  pkg/infra/models/sm_info.go
  pkg/infra/models/sm_request.go
  pkg/infra/models/sm_request_approval.go
  pkg/infra/models/sm_request_attachments.go
  pkg/infra/models/sm_request_participants.go
  pkg/infra/models/sm_service_desk_queue.go
  pkg/infra/models/sm_workspace.go
Labels: enhancement, Jira Software Cloud, Jira Service Management, Jira Agile, breaking-change, Jira Assets

#294 :green_heart: Upgraded the golang version to test/lint
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: enhancement
